services:
  gv_backend:
    env_file:
      - .env
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - gv_db
    environment:
    - NODE_ENV=development
    - CHOKIDAR_USEPOLLING=true

  gv_frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - gv_backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  gv_db:
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    image: postgis/postgis:17-3.5-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
