# backend/Dockerfile
FROM node:23-alpine

# Installer curl pour le health check
RUN apk add --no-cache curl

# Dossier de travail
WORKDIR /app

# Copie les fichiers de dépendances
COPY package*.json ./

# Installe TOUTES les dépendances (y compris dev)
RUN npm install --include=dev

# Copie le code après les dépendances
COPY . .

# Commande de démarrage
CMD ["npm", "run", "start:dev"]

